"""Curated catalog of Bible translations.

Each entry describes where the full text can be fetched from:

- ``source_type="open-bibles"`` — a file in the seven1m/open-bibles GitHub
  repo (OSIS, USFX, or Zefania XML).
- ``source_type="ebible"`` — a ``*_usfx.zip`` archive on eBible.org. Every
  ``ebible`` entry below is marked ``Redistributable`` in the eBible.org
  catalog, i.e. it may be freely downloaded and redistributed.
- ``source_type="youversion"`` — scraped chapter-by-chapter from bible.com
  for personal use (slow; prefer the other sources when available).
- ``source_type=None`` — copyrighted work with no free source; downloads
  produce a stub file pointing at the publisher.

Use :func:`search_catalog` to find translations offline (no network), or
:func:`get_catalog` for the whole list.
"""

OPEN_BIBLES_RAW = "https://raw.githubusercontent.com/seven1m/open-bibles/master"


def _open_bibles(filename):
    return f"{OPEN_BIBLES_RAW}/{filename}"


def _ebible_usfx(translation_id):
    return f"https://eBible.org/Scriptures/{translation_id}_usfx.zip"


POPULAR_TRANSLATIONS = [
    # ------------------------------------------------------------------
    # English — classic public-domain translations (open-bibles)
    # ------------------------------------------------------------------
    {
        "id": "eng-kjv",
        "abbreviation": "KJV",
        "name": "King James Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-kjv.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 3,
    },
    {
        "id": "eng-web",
        "abbreviation": "WEB",
        "name": "World English Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-web.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 12,
    },
    {
        "id": "eng-asv",
        "abbreviation": "ASV",
        "name": "American Standard Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-asv.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 13,
    },
    {
        "id": "eng-bbe",
        "abbreviation": "BBE",
        "name": "Bible in Basic English",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-bbe.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 14,
    },
    {
        "id": "eng-darby",
        "abbreviation": "DARBY",
        "name": "Darby Translation",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-darby.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 15,
    },
    {
        "id": "eng-dra",
        "abbreviation": "DRA",
        "name": "Douay-Rheims 1899",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-dra.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 16,
    },
    {
        "id": "eng-ylt",
        "abbreviation": "YLT",
        "name": "Young's Literal Translation",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-ylt.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 17,
    },
    {
        "id": "eng-oeb-us",
        "abbreviation": "OEB-US",
        "name": "Open English Bible (US Edition)",
        "language": "English",
        "language_code": "eng",
        "copyright": "CC0",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-us-oeb.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 18,
    },
    {
        "id": "eng-oeb-cw",
        "abbreviation": "OEB-CW",
        "name": "Open English Bible (Commonwealth Edition)",
        "language": "English",
        "language_code": "eng",
        "copyright": "CC0",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-gb-oeb.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 19,
    },
    {
        "id": "eng-webbe",
        "abbreviation": "WEBBE",
        "name": "World English Bible (British Edition)",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-gb-webbe.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 20,
    },
    # ------------------------------------------------------------------
    # English — modern free translations (eBible.org, redistributable)
    # ------------------------------------------------------------------
    {
        "id": "engbsb",
        "abbreviation": "BSB",
        "name": "Berean Standard Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Free for use (Berean Bible, bereanbible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engbsb_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 29,
    },
    {
        "id": "engfbv",
        "abbreviation": "FBV",
        "name": "Free Bible Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright 2018 Dr. Jonathan Gallagher",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engfbv_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 30,
    },
    {
        "id": "englsv",
        "abbreviation": "LSV",
        "name": "Literal Standard Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright 2020 Covenant Press",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/englsv_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 31,
    },
    {
        "id": "eng-gnv",
        "abbreviation": "GNV",
        "name": "Geneva Bible 1599",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/enggnv_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 32,
    },
    {
        "id": "engnet",
        "abbreviation": "NET",
        "name": "NET Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Biblical Studies Press (free for use)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engnet_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 33,
    },
    {
        "id": "eng-rv",
        "abbreviation": "RV",
        "name": "Revised Version 1895",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/eng-rv_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 34,
    },
    {
        "id": "engwmb",
        "abbreviation": "WMB",
        "name": "World Messianic Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engwmb_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 35,
    },
    {
        "id": "engULB",
        "abbreviation": "ULB",
        "name": "Unlocked Literal Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Door43 (CC BY-SA)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engULB_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 36,
    },
    {
        "id": "eng-t4t",
        "abbreviation": "T4T",
        "name": "Translation for Translators",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Ellis W. Deibler Jr. (free for use)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/eng-t4t_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 37,
    },
    {
        "id": "engwebster",
        "abbreviation": "WEBSTER",
        "name": "Noah Webster Bible 1833",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engwebster_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 38,
    },
    {
        "id": "engjps",
        "abbreviation": "JPS",
        "name": "JPS Tanakh 1917 (Old Testament)",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engjps_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 39,
    },
    {
        "id": "eng-Brenton",
        "abbreviation": "BRENTON",
        "name": "Brenton Septuagint Translation (Old Testament)",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/eng-Brenton_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 40,
    },
    {
        "id": "engkjvcpb",
        "abbreviation": "KJVPB",
        "name": "KJV Cambridge Paragraph Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engkjvcpb_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 41,
    },
    # ------------------------------------------------------------------
    # English — via YouVersion (personal use) and copyrighted stubs
    # ------------------------------------------------------------------
    {
        "id": "eng-niv",
        "abbreviation": "NIV",
        "name": "New International Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Biblica, Inc. (personal use only)",
        "freely_available": True,
        "source_url": None,
        "source_format": "youversion",
        "source_type": "youversion",
        "youversion_id": "111",
        "youversion_books": "niv",
        "popularity_rank": 1,
    },
    {
        "id": "eng-esv",
        "abbreviation": "ESV",
        "name": "English Standard Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Crossway",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 2,
    },
    {
        "id": "eng-nlt",
        "abbreviation": "NLT",
        "name": "New Living Translation",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Tyndale House",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 4,
    },
    {
        "id": "eng-nkjv",
        "abbreviation": "NKJV",
        "name": "New King James Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Thomas Nelson",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 5,
    },
    {
        "id": "eng-csb",
        "abbreviation": "CSB",
        "name": "Christian Standard Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Holman Bible Publishers",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 6,
    },
    {
        "id": "eng-nasb",
        "abbreviation": "NASB",
        "name": "New American Standard Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright The Lockman Foundation",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 7,
    },
    {
        "id": "eng-nrsv",
        "abbreviation": "NRSV",
        "name": "New Revised Standard Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright National Council of Churches",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 8,
    },
    {
        "id": "tpt",
        "abbreviation": "TPT",
        "name": "The Passion Translation",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Passion & Fire Ministries (personal use only)",
        "freely_available": True,
        "source_url": None,
        "source_format": "youversion",
        "source_type": "youversion",
        "youversion_id": "1849",
        "youversion_books": "tpt",
        "popularity_rank": 21,
    },
    {
        "id": "ptp",
        "abbreviation": "PTP",
        "name": "Patep New Testament (Yesu Xolac)",
        "language": "Patep",
        "language_code": "ptp",
        "copyright": "Copyright 1986 Wycliffe Bible Translators (CC BY-ND 4.0)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/ptp_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 22,
    },
    # ------------------------------------------------------------------
    # Spanish
    # ------------------------------------------------------------------
    {
        "id": "spa-rv1909",
        "abbreviation": "RV1909",
        "name": "Reina Valera 1909",
        "language": "Spanish",
        "language_code": "spa",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/spa-rv1909.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 9,
    },
    {
        "id": "spa-bes",
        "abbreviation": "BES",
        "name": "La Biblia en Español Sencillo",
        "language": "Spanish",
        "language_code": "spa",
        "copyright": "CC BY 4.0",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/spa-bes.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 23,
    },
    {
        "id": "spa-pddpt",
        "abbreviation": "PDDPT",
        "name": "Palabra de Dios para ti",
        "language": "Spanish",
        "language_code": "spa",
        "copyright": "Free for use (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/spa-pddpt.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 42,
    },
    {
        "id": "spa-vbl",
        "abbreviation": "VBL",
        "name": "Versión Biblia Libre",
        "language": "Spanish",
        "language_code": "spa",
        "copyright": "Free for use (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/spa-vbl.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 43,
    },
    {
        "id": "sparvg",
        "abbreviation": "RVG",
        "name": "Santa Biblia Reina Valera Gómez",
        "language": "Spanish",
        "language_code": "spa",
        "copyright": "Copyright Dr. Humberto Gómez (free via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/sparvg_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 44,
    },
    {
        "id": "spav1602p",
        "abbreviation": "V1602P",
        "name": "Santa Biblia Valera 1602 Purificada",
        "language": "Spanish",
        "language_code": "spa",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/spav1602p_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 45,
    },
    {
        "id": "spabll",
        "abbreviation": "BLL",
        "name": "Santa Biblia Libre Latinoamericano",
        "language": "Spanish",
        "language_code": "spa",
        "copyright": "Free via eBible.org",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/spabll_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 46,
    },
    # ------------------------------------------------------------------
    # German
    # ------------------------------------------------------------------
    {
        "id": "deu-luther1912",
        "abbreviation": "LUT1912",
        "name": "Luther Bible 1912",
        "language": "German",
        "language_code": "deu",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/deu-luther1912.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 24,
    },
    {
        "id": "deuelbbk",
        "abbreviation": "ELB",
        "name": "Elberfelder Übersetzung (bibelkommentare.de)",
        "language": "German",
        "language_code": "deu",
        "copyright": "Copyright Verbreitung des christlichen Glaubens (free via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/deuelbbk_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 47,
    },
    # ------------------------------------------------------------------
    # French
    # ------------------------------------------------------------------
    {
        "id": "fra-ostervald",
        "abbreviation": "OST",
        "name": "Ostervald 1996",
        "language": "French",
        "language_code": "fra",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/fra-ostervald.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 26,
    },
    {
        "id": "fraLSG",
        "abbreviation": "LSG",
        "name": "Louis Segond 1910",
        "language": "French",
        "language_code": "fra",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/fraLSG_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 48,
    },
    {
        "id": "fra_fob",
        "abbreviation": "FOB",
        "name": "La Sainte Bible (FOB)",
        "language": "French",
        "language_code": "fra",
        "copyright": "Free via eBible.org",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/fra_fob_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 49,
    },
    {
        "id": "frajnd",
        "abbreviation": "JND",
        "name": "Bible J.N. Darby (French)",
        "language": "French",
        "language_code": "fra",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/frajnd_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 50,
    },
    # ------------------------------------------------------------------
    # Portuguese
    # ------------------------------------------------------------------
    {
        "id": "por-almeida",
        "abbreviation": "ALM",
        "name": "João Ferreira de Almeida",
        "language": "Portuguese",
        "language_code": "por",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/por-almeida.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 25,
    },
    {
        "id": "porbr2018",
        "abbreviation": "BLIVRE",
        "name": "Bíblia Livre",
        "language": "Portuguese",
        "language_code": "por",
        "copyright": "Copyright 2018 Santos et al. (free via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/porbr2018_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 51,
    },
    {
        "id": "porbrbsl",
        "abbreviation": "BPM",
        "name": "Bíblia Portuguesa Mundial",
        "language": "Portuguese",
        "language_code": "por",
        "copyright": "Free via eBible.org",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/porbrbsl_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 52,
    },
    # ------------------------------------------------------------------
    # Russian
    # ------------------------------------------------------------------
    {
        "id": "rus-synodal",
        "abbreviation": "RUS",
        "name": "Russian Synodal Translation",
        "language": "Russian",
        "language_code": "rus",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/russyn_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 27,
    },
    # ------------------------------------------------------------------
    # Chinese
    # ------------------------------------------------------------------
    {
        "id": "chi-cuv",
        "abbreviation": "CUV",
        "name": "Chinese Union Version (Traditional)",
        "language": "Chinese (Traditional)",
        "language_code": "chi",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/chi-cuv.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 28,
    },
    {
        "id": "chi-cuv-simp",
        "abbreviation": "CUVS",
        "name": "Chinese Union Version (Simplified)",
        "language": "Chinese (Simplified)",
        "language_code": "chi",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/chi-cuv-simp.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 53,
    },
    {
        "id": "cmn-cu89s",
        "abbreviation": "CUV89S",
        "name": "新标点和合本 (Simplified, new punctuation)",
        "language": "Chinese (Simplified)",
        "language_code": "cmn",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/cmn-cu89s_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 54,
    },
    {
        "id": "cmn-cu89t",
        "abbreviation": "CUV89T",
        "name": "新標點和合本 (Traditional, new punctuation)",
        "language": "Chinese (Traditional)",
        "language_code": "cmn",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/cmn-cu89t_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 55,
    },
    # ------------------------------------------------------------------
    # Japanese
    # ------------------------------------------------------------------
    {
        "id": "jpn-kougo",
        "abbreviation": "KOUGO",
        "name": "Japanese Colloquial Version (口語訳)",
        "language": "Japanese",
        "language_code": "jpn",
        "copyright": "Copyright Japan Bible Society (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/jpn-kougo.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 56,
    },
    {
        "id": "jpn1965",
        "abbreviation": "SHINKAI",
        "name": "新改訳新約聖書 1965 (Shinkaiyaku New Testament)",
        "language": "Japanese",
        "language_code": "jpn",
        "copyright": "Public Domain (via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/jpn1965_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 57,
    },
    {
        "id": "jpnm",
        "abbreviation": "JFB",
        "name": "フリーダム・バイブル (Japanese Freedom Bible)",
        "language": "Japanese",
        "language_code": "jpn",
        "copyright": "Public Domain (via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/jpnm_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 58,
    },
    # ------------------------------------------------------------------
    # Korean
    # ------------------------------------------------------------------
    {
        "id": "kor",
        "abbreviation": "KRV",
        "name": "한국어 성경 (Korean Revised Version)",
        "language": "Korean",
        "language_code": "kor",
        "copyright": "Public Domain (via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/kor_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 59,
    },
    # ------------------------------------------------------------------
    # Italian
    # ------------------------------------------------------------------
    {
        "id": "ita-riveduta",
        "abbreviation": "RIV",
        "name": "Riveduta 1927",
        "language": "Italian",
        "language_code": "ita",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/ita-riveduta.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 60,
    },
    {
        "id": "ita1885",
        "abbreviation": "DIODATI",
        "name": "Diodati Bibbia 1885",
        "language": "Italian",
        "language_code": "ita",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/ita1885_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 61,
    },
    # ------------------------------------------------------------------
    # Dutch
    # ------------------------------------------------------------------
    {
        "id": "dut-statenvertaling",
        "abbreviation": "SVV",
        "name": "Statenvertaling",
        "language": "Dutch",
        "language_code": "nld",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/dut-statenvertaling.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 62,
    },
    {
        "id": "nld",
        "abbreviation": "NLD1917",
        "name": "De Heilige Schrift 1917",
        "language": "Dutch",
        "language_code": "nld",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/nld_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 63,
    },
    # ------------------------------------------------------------------
    # Arabic, Hindi
    # ------------------------------------------------------------------
    {
        "id": "arb-vd",
        "abbreviation": "VANDYKE",
        "name": "Arabic Van Dyke",
        "language": "Arabic",
        "language_code": "arb",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/arb-vd_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 64,
    },
    {
        "id": "hin2017",
        "abbreviation": "HINIRV",
        "name": "इंडियन रिवाइज्ड वर्जन (Hindi IRV)",
        "language": "Hindi",
        "language_code": "hin",
        "copyright": "Copyright Bridge Connectivity Solutions (free via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/hin2017_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 65,
    },
    # ------------------------------------------------------------------
    # Swahili, Tagalog, Vietnamese, Thai, Turkish, Indonesian
    # ------------------------------------------------------------------
    {
        "id": "swa-swahili",
        "abbreviation": "SWA",
        "name": "Biblia Takatifu (Swahili)",
        "language": "Swahili",
        "language_code": "swa",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/swa-swahili.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 66,
    },
    {
        "id": "swhulb",
        "abbreviation": "SWAULB",
        "name": "Biblia Takatifu (Swahili ULB)",
        "language": "Swahili",
        "language_code": "swa",
        "copyright": "Copyright Door43 (CC BY-SA)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/swhulb_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 67,
    },
    {
        "id": "tgl-tagalog",
        "abbreviation": "TGL",
        "name": "Tagalog Bible 1905",
        "language": "Tagalog",
        "language_code": "tgl",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/tgl-tagalog.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 68,
    },
    {
        "id": "tglulb",
        "abbreviation": "TGLULB",
        "name": "Banal na Bibliya (Tagalog ULB)",
        "language": "Tagalog",
        "language_code": "tgl",
        "copyright": "Copyright Door43 (CC BY-SA)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/tglulb_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 69,
    },
    {
        "id": "vie-cadman",
        "abbreviation": "VIE",
        "name": "Vietnamese Cadman Bible",
        "language": "Vietnamese",
        "language_code": "vie",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/vie-cadman.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 70,
    },
    {
        "id": "vie1934",
        "abbreviation": "VIE1934",
        "name": "Kinh Thánh 1934 (Vietnamese)",
        "language": "Vietnamese",
        "language_code": "vie",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/vie1934_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 71,
    },
    {
        "id": "tha-thai",
        "abbreviation": "THA",
        "name": "Thai Bible",
        "language": "Thai",
        "language_code": "tha",
        "copyright": "Free for use (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/tha-thai.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 72,
    },
    {
        "id": "thaKJV",
        "abbreviation": "THAKJV",
        "name": "พระคัมภีร์ภาษาไทยฉบับ KJV (Thai KJV)",
        "language": "Thai",
        "language_code": "tha",
        "copyright": "Copyright Philip Pope (free via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/thaKJV_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 73,
    },
    {
        "id": "tur-turkish",
        "abbreviation": "TUR",
        "name": "Kutsal Kitap (Turkish)",
        "language": "Turkish",
        "language_code": "tur",
        "copyright": "Free for use (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/tur-turkish.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 74,
    },
    {
        "id": "turytc",
        "abbreviation": "YTC",
        "name": "Yorumsuz Türkçe Çeviri (Turkish YTC)",
        "language": "Turkish",
        "language_code": "tur",
        "copyright": "Copyright Serinken/eBible.org (free via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/turytc_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 75,
    },
    {
        "id": "indayt",
        "abbreviation": "AYT",
        "name": "Alkitab Yang Terbuka (Indonesian)",
        "language": "Indonesian",
        "language_code": "ind",
        "copyright": "Copyright YLSA-AYT (free via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/indayt_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 76,
    },
    # ------------------------------------------------------------------
    # Biblical languages: Greek, Hebrew, Latin
    # ------------------------------------------------------------------
    {
        "id": "grcbyz",
        "abbreviation": "BYZ",
        "name": "Byzantine Majority Greek New Testament",
        "language": "Greek (Koine)",
        "language_code": "grc",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/grcbyz_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 77,
    },
    {
        "id": "grcsbl",
        "abbreviation": "SBLGNT",
        "name": "SBL Greek New Testament",
        "language": "Greek (Koine)",
        "language_code": "grc",
        "copyright": "Copyright Society of Biblical Literature (free for use)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/grcsbl_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 78,
    },
    {
        "id": "grclxx",
        "abbreviation": "LXX",
        "name": "Septuagint in Greek (Old Testament)",
        "language": "Greek (Koine)",
        "language_code": "grc",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/grclxx_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 79,
    },
    {
        "id": "hboWLC",
        "abbreviation": "WLC",
        "name": "Westminster Leningrad Codex (Hebrew Old Testament)",
        "language": "Hebrew",
        "language_code": "hbo",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/hboWLC_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 80,
    },
    {
        "id": "heb",
        "abbreviation": "HEBMOD",
        "name": "תנ״ך עברי מודרני (Modern Hebrew Bible)",
        "language": "Hebrew",
        "language_code": "heb",
        "copyright": "Public Domain (via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/heb_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 81,
    },
    {
        "id": "lat-clementine",
        "abbreviation": "VUL",
        "name": "Clementine Vulgate (Latin)",
        "language": "Latin",
        "language_code": "lat",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/lat-clementine.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 82,
    },
    # ------------------------------------------------------------------
    # Rest of Europe and beyond (open-bibles + eBible)
    # ------------------------------------------------------------------
    {
        "id": "fin-biblia",
        "abbreviation": "FIN1776",
        "name": "Finnish Biblia 1776",
        "language": "Finnish",
        "language_code": "fin",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/fin-biblia.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 83,
    },
    {
        "id": "swe-swedish",
        "abbreviation": "SWE",
        "name": "Swedish Bible",
        "language": "Swedish",
        "language_code": "swe",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/swe-swedish.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 84,
    },
    {
        "id": "nor-norwegian",
        "abbreviation": "NOR",
        "name": "Norwegian Bible",
        "language": "Norwegian",
        "language_code": "nor",
        "copyright": "Free for use (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/nor-norwegian.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 85,
    },
    {
        "id": "dan-danish",
        "abbreviation": "DAN",
        "name": "Danish Bible",
        "language": "Danish",
        "language_code": "dan",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/dan-danish.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 86,
    },
    {
        "id": "pol-gdanska",
        "abbreviation": "GDANSKA",
        "name": "Biblia Gdańska (Polish)",
        "language": "Polish",
        "language_code": "pol",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/pol-gdanska.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 87,
    },
    {
        "id": "polubg",
        "abbreviation": "UBG",
        "name": "Święta Biblia (Polish UBG)",
        "language": "Polish",
        "language_code": "pol",
        "copyright": "Copyright Fundacja Wrota Nadziei (free via eBible.org)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/polubg_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 88,
    },
    {
        "id": "ces1613",
        "abbreviation": "BKR",
        "name": "Bible Kralická 1613 (Czech)",
        "language": "Czech",
        "language_code": "ces",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/ces1613_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 89,
    },
    {
        "id": "cze-bkr",
        "abbreviation": "CZEBKR",
        "name": "Czech Bible Kralická (Zefania)",
        "language": "Czech",
        "language_code": "ces",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/cze-bkr.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 90,
    },
    {
        "id": "hun-karoli",
        "abbreviation": "KAROLI",
        "name": "Károli Gáspár Bible (Hungarian)",
        "language": "Hungarian",
        "language_code": "hun",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/hun-karoli.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 91,
    },
    {
        "id": "hrv-croatian",
        "abbreviation": "HRV",
        "name": "Croatian Bible",
        "language": "Croatian",
        "language_code": "hrv",
        "copyright": "Free for use (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/hrv-croatian.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 92,
    },
    {
        "id": "lav-latvian",
        "abbreviation": "LAV",
        "name": "Latvian Bible",
        "language": "Latvian",
        "language_code": "lav",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/lav-latvian.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 93,
    },
    {
        "id": "sqi-albanian",
        "abbreviation": "SQI",
        "name": "Albanian Bible",
        "language": "Albanian",
        "language_code": "sqi",
        "copyright": "Free for use (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/sqi-albanian.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 94,
    },
    {
        "id": "ron-rccv",
        "abbreviation": "RCCV",
        "name": "Biblia în Română (RCCV)",
        "language": "Romanian",
        "language_code": "ron",
        "copyright": "Free for use (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/ron-rccv.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 95,
    },
    {
        "id": "ron1924",
        "abbreviation": "CORNI",
        "name": "Biblia Dumitru Cornilescu 1924 (Romanian)",
        "language": "Romanian",
        "language_code": "ron",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/ron1924_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 96,
    },
    {
        "id": "ukr1871",
        "abbreviation": "KULISH",
        "name": "Біблія Куліша (Ukrainian Kulish 1905)",
        "language": "Ukrainian",
        "language_code": "ukr",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/ukr1871_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 97,
    },
    {
        "id": "bul-bulgarian",
        "abbreviation": "BUL",
        "name": "Bulgarian Bible",
        "language": "Bulgarian",
        "language_code": "bul",
        "copyright": "Free for use (via open-bibles)",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/bul-bulgarian.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 98,
    },
    {
        "id": "mri-maori",
        "abbreviation": "MAORI",
        "name": "Te Paipera Tapu (Māori)",
        "language": "Māori",
        "language_code": "mri",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/mri-maori.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 99,
    },
    {
        "id": "chr-cherokee",
        "abbreviation": "CHR",
        "name": "Cherokee New Testament",
        "language": "Cherokee",
        "language_code": "chr",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/chr-cherokee.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 100,
    },
]


def get_catalog():
    return POPULAR_TRANSLATIONS


def get_translation(translation_id: str):
    for t in POPULAR_TRANSLATIONS:
        if t["id"] == translation_id:
            return t
    return None


def get_by_abbreviation(abbreviation: str):
    """Find a translation by abbreviation (case-insensitive) or id."""
    if not abbreviation:
        return None
    key = abbreviation.strip().lower()
    for t in POPULAR_TRANSLATIONS:
        if t["abbreviation"].lower() == key or t.get("id", "").lower() == key:
            return t
    return None


def search_catalog(query: str = "", language: str = ""):
    """Offline search of the curated catalog by name/abbreviation/language."""
    q = (query or "").strip().lower()
    lang = (language or "").strip().lower()
    results = []
    for t in POPULAR_TRANSLATIONS:
        hay = " ".join(
            str(t.get(k, "")) for k in ("abbreviation", "name", "id", "language")
        ).lower()
        if q and q not in hay:
            continue
        if lang and lang not in t.get("language", "").lower():
            continue
        results.append(t)
    return sorted(results, key=lambda t: t.get("popularity_rank", 99))


def list_languages():
    """Sorted list of language names covered by the catalog."""
    return sorted({t.get("language", "") for t in POPULAR_TRANSLATIONS if t.get("language")})


def get_freely_available():
    return [t for t in POPULAR_TRANSLATIONS if t["freely_available"]]


def get_copyrighted():
    return [t for t in POPULAR_TRANSLATIONS if not t["freely_available"]]
