POPULAR_TRANSLATIONS = [
    {
        "id": "eng-kjv",
        "abbreviation": "KJV",
        "name": "King James Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-kjv.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 3,
    },
    {
        "id": "eng-web",
        "abbreviation": "WEB",
        "name": "World English Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-web.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 12,
    },
    {
        "id": "eng-asv",
        "abbreviation": "ASV",
        "name": "American Standard Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-asv.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 13,
    },
    {
        "id": "eng-bbe",
        "abbreviation": "BBE",
        "name": "Bible in Basic English",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-bbe.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 14,
    },
    {
        "id": "eng-darby",
        "abbreviation": "DARBY",
        "name": "Darby Translation",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-darby.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 15,
    },
    {
        "id": "eng-dra",
        "abbreviation": "DRA",
        "name": "Douay-Rheims 1899",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-dra.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 16,
    },
    {
        "id": "eng-ylt",
        "abbreviation": "YLT",
        "name": "Young's Literal Translation",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-ylt.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 17,
    },
    {
        "id": "eng-oeb-us",
        "abbreviation": "OEB-US",
        "name": "Open English Bible (US Edition)",
        "language": "English",
        "language_code": "eng",
        "copyright": "CC0",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-us-oeb.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 18,
    },
    {
        "id": "eng-oeb-cw",
        "abbreviation": "OEB-CW",
        "name": "Open English Bible (Commonwealth Edition)",
        "language": "English",
        "language_code": "eng",
        "copyright": "CC0",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-gb-oeb.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 19,
    },
    {
        "id": "eng-webbe",
        "abbreviation": "WEBBE",
        "name": "World English Bible (British Edition)",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/eng-gb-webbe.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 20,
    },
    {
        "id": "eng-niv",
        "abbreviation": "NIV",
        "name": "New International Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Biblica, Inc.",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 1,
    },
    {
        "id": "eng-esv",
        "abbreviation": "ESV",
        "name": "English Standard Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Crossway",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 2,
    },
    {
        "id": "eng-nlt",
        "abbreviation": "NLT",
        "name": "New Living Translation",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Tyndale House",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 4,
    },
    {
        "id": "eng-nkjv",
        "abbreviation": "NKJV",
        "name": "New King James Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Thomas Nelson",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 5,
    },
    {
        "id": "eng-csb",
        "abbreviation": "CSB",
        "name": "Christian Standard Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Holman Bible Publishers",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 6,
    },
    {
        "id": "eng-nasb",
        "abbreviation": "NASB",
        "name": "New American Standard Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright The Lockman Foundation",
        "freely_available": False,
        "source_url": "https://ebible.org/engnasb/",
        "source_format": None,
        "source_type": "ebible",
        "popularity_rank": 7,
    },
    {
        "id": "eng-nrsv",
        "abbreviation": "NRSV",
        "name": "New Revised Standard Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright National Council of Churches",
        "freely_available": False,
        "source_url": None,
        "source_format": None,
        "source_type": None,
        "popularity_rank": 8,
    },
    {
        "id": "tpt",
        "abbreviation": "TPT",
        "name": "The Passion Translation",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright Passion & Fire Ministries",
        "freely_available": True,
        "source_url": None,
        "source_format": "youversion",
        "source_type": "youversion",
        "popularity_rank": 21,
    },
    {
        "id": "ptp",
        "abbreviation": "PTP",
        "name": "Patep New Testament (Yesu Xolac)",
        "language": "Patep",
        "language_code": "ptp",
        "copyright": "Copyright 1986 Wycliffe Bible Translators (CC BY-ND 4.0)",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/ptp_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 22,
    },
    {
        "id": "spa-rv1909",
        "abbreviation": "RV1909",
        "name": "Reina Valera 1909",
        "language": "Spanish",
        "language_code": "spa",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/spa-rv1909.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 9,
    },
    {
        "id": "spa-bes",
        "abbreviation": "BES",
        "name": "La Biblia en Espa\u00f1ol Sencillo",
        "language": "Spanish",
        "language_code": "spa",
        "copyright": "CC BY 4.0",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/spa-bes.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 23,
    },
    {
        "id": "deu-luther1912",
        "abbreviation": "LUT1912",
        "name": "Luther Bible 1912",
        "language": "German",
        "language_code": "deu",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/deu-luther1912.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 24,
    },
    {
        "id": "por-almeida",
        "abbreviation": "ALM",
        "name": "Jo\u00e3o Ferreira de Almeida",
        "language": "Portuguese",
        "language_code": "por",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/por-almeida.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 25,
    },
    {
        "id": "fra-ostervald",
        "abbreviation": "OST",
        "name": "Ostervald 1996",
        "language": "French",
        "language_code": "fra",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/fra-ostervald.osis.xml",
        "source_format": "osis",
        "source_type": "open-bibles",
        "popularity_rank": 26,
    },
    {
        "id": "rus-synodal",
        "abbreviation": "RUS",
        "name": "Russian Synodal Translation",
        "language": "Russian",
        "language_code": "rus",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/rus-synodal.zefania.xml",
        "source_format": "zefania",
        "source_type": "open-bibles",
        "popularity_rank": 27,
    },
    {
        "id": "chi-cuv",
        "abbreviation": "CUV",
        "name": "Chinese Union Version",
        "language": "Chinese (Traditional)",
        "language_code": "chi",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://raw.githubusercontent.com/seven1m/open-bibles/master/chi-cuv.usfx.xml",
        "source_format": "usfx",
        "source_type": "open-bibles",
        "popularity_rank": 28,
    },
    {
        "id": "engbsb",
        "abbreviation": "BSB",
        "name": "Berean Standard Bible",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engbsb_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 29,
    },
    {
        "id": "engfbv",
        "abbreviation": "FBV",
        "name": "Free Bible Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright 2018 Dr. Jonathan Gallagher",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/engfbv_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 30,
    },
    {
        "id": "englsv",
        "abbreviation": "LSV",
        "name": "Literal Standard Version",
        "language": "English",
        "language_code": "eng",
        "copyright": "Copyright 2020 Covenant Press",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/englsv_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 31,
    },
    {
        "id": "eng-gnv",
        "abbreviation": "GNV",
        "name": "Geneva Bible 1599",
        "language": "English",
        "language_code": "eng",
        "copyright": "Public Domain",
        "freely_available": True,
        "source_url": "https://eBible.org/Scriptures/enggnv_usfx.zip",
        "source_format": "usfx",
        "source_type": "ebible",
        "popularity_rank": 32,
    },
]


def get_catalog():
    return POPULAR_TRANSLATIONS


def get_translation(translation_id: str):
    for t in POPULAR_TRANSLATIONS:
        if t["id"] == translation_id:
            return t
    return None


def get_freely_available():
    return [t for t in POPULAR_TRANSLATIONS if t["freely_available"]]


def get_copyrighted():
    return [t for t in POPULAR_TRANSLATIONS if not t["freely_available"]]
